# CAC Analysis 2
#### Equations
(1) 76.55 = S<sub>M</sub> + S<sub>G</sub> + S<sub>S</sub> + S<sub>Holo</sub>  
(2) 45.83 = S<sub>G</sub> + S<sub>S</sub> + S<sub>HP</sub> + S<sub>VR</sub>  
(3) 87.66 = S<sub>M</sub> + S<sub>Vi</sub>  
(4) 100 = S<sub>M</sub> + S<sub>G</sub> + S<sub>S</sub> + S<sub>HP</sub>

In [1]:
# Setting variables up
import sympy as sym
from sympy import *
from cvxopt import matrix, solvers
M,G,S,Hp,Holo,VR,Vi = symbols('M G S Hp Holo VR Vi')

In [2]:
def listIntToDouble(lst):
    return [float(i) for i in lst]

In [3]:
def nestedToDouble(nested):
    for row in range(len(nested)):
        nested[row] = listIntToDouble(nested[row])
    return nested

In [7]:
print(sym.expand((M+Vi-87.66)**2))

M**2 + 2*M*Vi - 175.32*M + Vi**2 - 175.32*Vi + 7684.2756


In [4]:
# optimize with respect to Equation 3
P = matrix([
    [1.0,0.0,0.0,0.0,0.0,0.0,1.0],
    [0.0,0.0,0.0,0.0,0.0,0.0,0.0],
    [0.0,0.0,0.0,0.0,0.0,0.0,0.0],
    [0.0,0.0,0.0,0.0,0.0,0.0,0.0],
    [0.0,0.0,0.0,0.0,0.0,0.0,0.0],
    [0.0,0.0,0.0,0.0,0.0,0.0,0.0],
    [1.0,0.0,0.0,0.0,0.0,0.0,1.0],
    ])
q = matrix([-175.32,0,0,0,0,0,-175.32])

# Variable contraints
G = matrix(
#         [
#         [1.0,-1.0,0.0 ,0.0 ,0.0,],
#         [0.0, 1.0,-1.0,0.0 ,0.0,],
#         [0.0, 0.0,0.0 ,1.0 ,-1.0,],
#         [0.0, 0.0,1.0 ,-1.0,0.0,],
#         [0.0, 0.0,0.0 ,0.0 ,0.0,],
#         [0.0, 0.0,0.0 ,0.0 ,0.0,],
#         [0.0, 0.0,0.0 ,0.0 ,0.0,],
#     ]
    [
        [1.0,-1.0,0.0 ,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 1.0,-1.0,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,1.0 ,-1.0,0.0,0.0,0.0],
        [0.0, 0.0,1.0 ,-1.0,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,-1.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,-1.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,0.0,-1.0],
    ]
)

# h = matrix([100.0,0.0,0.0,0.0,0.0,])
h = matrix([100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
# Ax = b equation
A = matrix([
    [1.0,0.0,1.0],#M
    [1.0,1.0,1.0],#G
    [1.0,1.0,1.0],#S
    [0.0,1.0,1.0],#Hp
    [1.0,0.0,0.0],#Holo
    [0.0,1.0,0.0],#Vr
    [0.0,0.0,0.0],#Vi
    ])

b = matrix([76.55,45.83,100])
sol=solvers.qp(P,q, G, h, A, b)
for key in sol:
    print(key, sol[key])

     pcost       dcost       gap    pres   dres
 0: -1.4008e+04 -1.5548e+04  6e+03  5e-01  4e-01
 1: -1.5364e+04 -1.5825e+04  8e+02  4e-02  3e-02
 2: -1.5368e+04 -1.5404e+04  1e+02  7e-03  6e-03
 3: -1.5368e+04 -1.5009e+04  9e+01  6e-03  5e-03
 4: -1.5368e+04  1.2580e+04  1e+02  6e-03  5e-03
 5: -1.5368e+04  1.9428e+07  1e+03  6e-03  5e-03
 6: -1.5368e+04  9.4965e+14  6e+16  6e-01  5e-03
 7:  9.9118e+23 -9.9118e+23  2e+24  6e-01  5e-03
 8:  9.9118e+23 -9.9118e+23  2e+24  6e-01  7e-01
 9:  9.9118e+23 -9.9118e+23  2e+24  6e-01  8e-01
10:  9.9118e+23 -9.9118e+23  2e+24  6e-01  1e+00
11:  9.9118e+23 -9.9119e+23  2e+24  6e-01  2e+00
12:  9.9117e+23 -9.9119e+23  2e+24  6e-01  3e+00
13:  9.9116e+23 -9.9119e+23  2e+24  6e-01  6e+00
14:  9.9108e+23 -9.9119e+23  2e+24  6e-01  2e+01
15:  9.9092e+23 -9.9121e+23  2e+24  6e-01  1e+02
16:  9.9026e+23 -9.9122e+23  2e+24  6e-01  2e+02
17:  9.8875e+23 -9.9140e+23  2e+24  6e-01  2e+03
18:  9.8247e+23 -9.9150e+23  2e+24  6e-01  3e+03
19:  9.6796e+23 -9.93

In [9]:
import sympy as sym
from sympy import *
from cvxopt import matrix, solvers
M,G,S,Hp,Holo,VR,Vi = symbols('M G S Hp Holo VR Vi')
print("Equation = " ,sym.expand((M+G+S+Holo-76.55)**2))
#solving with respext to equation 1
P = [
    [1,1,1,0,1,0,0],
    [1,1,1,0,1,0,0],
    [1,1,1,0,1,0,0],
    [0,0,0,0,0,0,0],
    [1,1,1,0,1,0,0],
    [0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0],
]
P = matrix(nestedToDouble(P))
q = matrix([-153.1,-153.1,-153.1,0,-153.1,0,0])
# Variable contraints
G = matrix(
#     [
#         [1.0,-1.0,0.0,0.0,0.0],
#         [0.0,1.0,-1.0,0.0,0.0],
#         [0.0,0.0,0.0,1.0,-1.0],
#         [0.0,0.0,1.0,-1.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#     ]
        [
        [1.0,-1.0,0.0 ,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 1.0,-1.0,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,1.0 ,-1.0,0.0,0.0,0.0],
        [0.0, 0.0,1.0 ,-1.0,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,-1.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,-1.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,0.0,-1.0],
        ]
)
# h = matrix([100.0,0.0,0.0,0.0,0.0])
h = matrix([100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
# Ax = b equation
A = [
    [0,1,1],#M
    [1,0,1],#G
    [1,0,1],#S
    [1,0,1],#Hp
    [0,0,0],#Holo
    [1,0,0],#Vr
    [0,1,0],#Vi
    ]
A = matrix(nestedToDouble(A))
b = matrix([45.83,87.66,100])
print("p rank =",np.linalg.matrix_rank(P))
print("A rank =",np.linalg.matrix_rank(A))
print("G rank =",np.linalg.matrix_rank(G))
print(P)
sol=solvers.qp(P,q, G, h, A, b)
for key in sol:
    print(key, sol[key])

Equation =  G**2 + 2*G*Holo + 2*G*M + 2*G*S - 153.1*G + Holo**2 + 2*Holo*M + 2*Holo*S - 153.1*Holo + M**2 + 2*M*S - 153.1*M + S**2 - 153.1*S + 5859.9025
p rank = 1
A rank = 3
G rank = 7
[ 1.00e+00  1.00e+00  1.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[ 1.00e+00  1.00e+00  1.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[ 1.00e+00  1.00e+00  1.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 1.00e+00  1.00e+00  1.00e+00  0.00e+00  1.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]
[ 0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00  0.00e+00]

     pcost       dcost       gap    pres   dres
 0: -1.1358e+04 -1.2554e+04  1e+03  6e-02  2e-01
 1: -1.1719e+04 -1.1940e+04  2e+02  1e-03  5e-03
 2: -1.1720e+04 -1.1722e+04  2e+00  1e-05  5e-05
 3: -1.1720e+04 -1.1720e+04  2e-02  1e-07  5e-07
 4: -1.1720e+04 -1.1720e+04  2e-04  1e-09  5e-09
Optimal solution

In [4]:
print("THIS IS NOT CORRECT")
import sympy as sym
from sympy import *
from cvxopt import matrix, solvers
import numpy as np
# # M,G,S,Hp,Holo,VR,Vi = symbols('M G S Hp Holo VR Vi')
# print("Equation =",sym.expand(((M+G+S+Holo-76.55)**2) + (G+S+Hp+VR-45.83)**2 + (M+Vi-87.66)**2 + (M+G+S+Hp-100)**2))

P = [
    [3,4,0,2,2,0,0],
    [0,3,0,0,0,0,0],
    [4,6,3,2,2,0,0],
    [0,4,0,2,0,0,0],
    [0,2,0,0,1,0,0],
    [0,2,2,0,0,1,0],
    [2,0,0,0,0,0,1]
]
P = matrix(nestedToDouble(P))
# q = matrix([-528.42, -444.76,-444.76,-291.66,-153.1,-91.66,-175.32])
q = matrix([-528.42, -444.76,-444.76,-291.66,-153.1,-91.66,0])
# Variable contraints
G = matrix(
#     [
#         [1.0,-1.0,0.0,0.0,0.0],
#         [0.0,1.0,-1.0,0.0,0.0],
#         [0.0,0.0,0.0,1.0,-1.0],
#         [0.0,0.0,1.0,-1.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#         [0.0,0.0,0.0,0.0,0.0],
#     ]
        [
        [1.0,-1.0,0.0 ,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 1.0,-1.0,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,1.0 ,-1.0,0.0,0.0,0.0],
        [0.0, 0.0,1.0 ,-1.0,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,-1.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,-1.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,0.0,-1.0],
        ]
)
# h = matrix([100.0,0.0,0.0,0.0,0.0])
h = matrix([100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
# Ax = b equation
A = [
    [1,0,1,1, ],#M
    [1,1,0,1, ],#G
    [0,1,0,1, ],#S
    [0,1,0,1,],#Hp
    [1,0,0,0, ],#Holo
    [0,1,0,0, ],#Vr
    [0,0,1,0,],#Vi 
    ]
A = matrix(nestedToDouble(A))
b = matrix([76.55, 45.83,87.66,100])
print("p rank =",np.linalg.matrix_rank(P))
print("A rank =",np.linalg.matrix_rank(A))
print("G rank =",np.linalg.matrix_rank(G))
sol=solvers.qp(P,q, G, h, A, b)
for key in sol:
    print(key, sol[key])

THIS IS NOT CORRECT
p rank = 7
A rank = 4
G rank = 7


ValueError: Rank(A) < p or Rank([P; A; G]) < n

Matrix 𝐴 define
s the equality constraints of the problem and p is the number of equality constraints (thus the number of rows in A). While matrix 𝐺 defines the inequality constraint. And finally, 𝑛 is the number of variables in your optimization (size of 𝑥).

rank([𝐺,𝐴])<𝑛 means that the combination of your equality and inequality constraints do not span the whole free variable space of your optimization and thus it is a unbounded Linear Programming (optimal 𝑡=−∞). While rank(𝐴)<𝑝 means that the equality constraints are ill defined.

From the fact that you do not have equality constraints I'd assume you have the second. And why is answered in your third question.

3) Since 𝐴𝑇𝑃+𝑃𝐴<0 already has a solution, it is easy to see that 𝐾≡0 is a solution to your problem. However, there are infinitely other solutions that results in the same value of 𝑡. This causes your system to be have infinite valid solutions and be ill-defined (rank([𝐺,𝐴])<𝑛) for this specific solver.

4) Be sure that for any choice of matrix C is system is output controllable. If you problem had a high number of states this would help since the optimization would be too big, but for the size you have it shouldn't be a problem.

In [11]:
import sympy as sym
from sympy import *
from cvxopt import matrix, solvers
M,G,S,Hp,Holo,VR,Vi = symbols('M G S Hp Holo VR Vi')
print("Equation =",sym.expand(((M+G+S+Holo-76.55)**2) + (G+S+Hp+VR-45.83)**2 + (M+Vi-87.66)**2))

Equation = 2*G**2 + 2*G*Holo + 2*G*Hp + 2*G*M + 4*G*S + 2*G*VR - 244.76*G + Holo**2 + 2*Holo*M + 2*Holo*S - 153.1*Holo + Hp**2 + 2*Hp*S + 2*Hp*VR - 91.66*Hp + 2*M**2 + 2*M*S + 2*M*Vi - 328.42*M + 2*S**2 + 2*S*VR - 244.76*S + VR**2 - 91.66*VR + Vi**2 - 175.32*Vi + 15644.567


## BELOW IS THE OPTIMAL SOLUTION THAT I CAN FIND

In [10]:
P = [
    [2,1,0,0,1,1,0],
    [1,2,1,1,1,0,0],
    [0,1,2,2,2,0,0],
    [0,1,0,1,0,0,0],
    [1,1,0,0,1,0,0],
    [0,1,2,2,0,1,0],
    [2,0,0,0,0,0,1]
]
P = matrix(nestedToDouble(P))
# q = matrix([-528.42, -444.76,-444.76,-291.66,-153.1,-91.66,-175.32])
q = matrix([-328.42,-244.76,-244.76,-91.66,-153.1,-91.66,-175.32])
# Variable contraints
G = matrix(
        [
        [1.0,-1.0,0.0 ,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 1.0,-1.0,0.0 ,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,1.0 ,-1.0,0.0,0.0,0.0],
        [0.0, 0.0,1.0 ,-1.0,0.0,0.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,-1.0,0.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,-1.0,0.0],
        [0.0, 0.0,0.0 ,0.0 ,0.0,0.0,0.0,-1.0],
        ]
)
# h = matrix([100.0,0.0,0.0,0.0,0.0])
h = matrix([100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
# Ax = b equation
A = [
#     [1,0,1,1, ],#M
#     [1,1,0,1, ],#G
#     [0,1,0,1, ],#S
#     [0,1,0,1,],#Hp
#     [1,0,0,0, ],#Holo
#     [0,1,0,0, ],#Vr
#     [0,0,1,0,],#Vi 
    [1],
    [1],
    [1],
    [1],
    [0],
    [0],
    [0]
    ]
A = matrix(nestedToDouble(A))
# b = matrix([76.55, 45.83,87.66,100])
b=matrix([100.0])
print("p rank =",np.linalg.matrix_rank(P))
print("A rank =",np.linalg.matrix_rank(A))
print("G rank =",np.linalg.matrix_rank(G))
sol=solvers.qp(P,q, G, h, A, b)
for key in sol:
    print(key, sol[key])

p rank = 7
A rank = 1
G rank = 7
     pcost       dcost       gap    pres   dres
 0: -3.8381e+04 -3.9699e+04  3e+04  1e+00  3e-01
 1: -3.9334e+04 -4.2290e+04  3e+03  1e-02  3e-03
 2: -3.9623e+04 -4.0127e+04  5e+02  2e-03  4e-04
Terminated (singular KKT matrix).
x [ 7.27e+01]
[ 1.80e+01]
[ 4.50e+00]
[ 4.88e+00]
[ 5.36e+01]
[ 2.40e+01]
[ 1.75e+02]

y [ 8.26e+01]

s [ 2.74e+01]
[ 5.48e+01]
[ 1.31e+01]
[ 4.52e-01]
[ 4.57e+00]
[ 5.36e+01]
[ 2.40e+01]
[ 1.75e+02]

z [ 5.17e+00]
[ 1.65e-01]
[ 9.51e+00]
[ 3.22e+01]
[ 1.39e+01]
[ 2.06e-01]
[ 5.10e+00]
[ 1.21e-01]

status unknown
gap 508.4778527096033
relative gap 0.012832931012330935
primal objective -39622.89302584234
dual objective -40126.821551166104
primal infeasibility 0.001936921127170754
dual infeasibility 0.00037598123116638156
primal slack 0.4517590766317799
dual slack 0.12057046816179513
iterations 2
